In [86]:

!pip install --upgrade pip


!pip install pandas
!pip install numpy


!pip install scikit-learn

!pip install xgboost


!pip install imbalanced-learn

!pip install matplotlib
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: To modify pip, please run the following command:
C:\Program Files\Python313\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [87]:
# Library
import pandas as pd
import numpy as np
from collections import Counter

# Preprocessing & split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Metrics
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
# Model
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

# Imbalanced learning (undersampling)
from imblearn.under_sampling import RandomUnderSampler, ClusterCentroids, TomekLinks, EditedNearestNeighbours

# Misc
import warnings
warnings.filterwarnings('ignore')


In [88]:
# Load CSV
df = pd.read_csv("diabetes_dataset.csv")

# Cek 5 baris pertama
print(df.head())

   year  gender   age location  race:AfricanAmerican  race:Asian  \
0  2020  Female  32.0  Alabama                     0           0   
1  2015  Female  29.0  Alabama                     0           1   
2  2015    Male  18.0  Alabama                     0           0   
3  2015    Male  41.0  Alabama                     0           0   
4  2016  Female  52.0  Alabama                     1           0   

   race:Caucasian  race:Hispanic  race:Other  hypertension  heart_disease  \
0               0              0           1             0              0   
1               0              0           0             0              0   
2               0              0           1             0              0   
3               1              0           0             0              0   
4               0              0           0             0              0   

  smoking_history    bmi  hbA1c_level  blood_glucose_level  diabetes  
0           never  27.32          5.0                  10

In [89]:
df = df.drop_duplicates()


In [90]:
df = df.drop(columns=["year", "location"])


In [91]:
df = pd.get_dummies(df, columns=["gender", "smoking_history"], drop_first=True)


In [92]:
X = df.drop("diabetes", axis=1)
y = df["diabetes"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)


In [93]:
# 5️⃣ Random Forest
# ===============================
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'  # penting supaya minoritas terbaca
)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("\n=== Random Forest (Data Asli) ===")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

# ===============================
# 6️⃣ XGBoost
# ===============================
xgb = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

print("\n=== XGBoost (Data Asli) ===")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))


=== Random Forest (Data Asli) ===
Accuracy: 0.970997099709971
F1 Score: 0.7997237569060773
Confusion Matrix:
 [[18260    38]
 [  542  1158]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98     18298
           1       0.97      0.68      0.80      1700

    accuracy                           0.97     19998
   macro avg       0.97      0.84      0.89     19998
weighted avg       0.97      0.97      0.97     19998


=== XGBoost (Data Asli) ===
Accuracy: 0.96994699469947
F1 Score: 0.7968908415005069
Confusion Matrix:
 [[18218    80]
 [  521  1179]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98     18298
           1       0.94      0.69      0.80      1700

    accuracy                           0.97     19998
   macro avg       0.95      0.84      0.89     19998
weighted avg       0.97      0.97      0.97     19998



In [94]:
from imblearn.under_sampling import TomekLinks
# ===============================
# 1️⃣ Resampling dengan Tomek Links
# ===============================
tl = TomekLinks()
X_res, y_res = tl.fit_resample(X_train, y_train)
print("Distribusi setelah Tomek Links:", Counter(y_res))

# 2️⃣ Random Forest
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)
rf.fit(X_res, y_res)
y_pred_rf = rf.predict(X_test)

print("\n=== Random Forest  ===")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf, pos_label=1))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

# 3️⃣ XGBoost
xgb = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)
xgb.fit(X_res, y_res)
y_pred_xgb = xgb.predict(X_test)

print("\n=== XGBoost ===")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb, pos_label=1))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))

Distribusi setelah Tomek Links: Counter({0: 72119, 1: 6800})

=== Random Forest  ===
Accuracy: 0.9705970597059705
F1 Score: 0.7990430622009569
Confusion Matrix:
 [[18241    57]
 [  531  1169]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98     18298
           1       0.95      0.69      0.80      1700

    accuracy                           0.97     19998
   macro avg       0.96      0.84      0.89     19998
weighted avg       0.97      0.97      0.97     19998


=== XGBoost ===
Accuracy: 0.9720972097209721
F1 Score: 0.8036593947923997
Confusion Matrix:
 [[18298     0]
 [  558  1142]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98     18298
           1       1.00      0.67      0.80      1700

    accuracy                           0.97     19998
   macro avg       0.99      0.84      0.89     19998
weighted avg       0.97      0.97  

In [ ]:
# =========================
# 0️⃣ Library
# =========================
import pandas as pd
import pickle
from collections import Counter
from xgboost import XGBClassifier
from imblearn.under_sampling import TomekLinks
import warnings
warnings.filterwarnings('ignore')

# =========================
# 1️⃣ Load dataset training
# =========================
data = pd.read_csv("diabetes_dataset.csv")  # dataset asli dengan target 'diabetes'
X = data.drop("diabetes", axis=1)
y = data["diabetes"]

# =========================
# 2️⃣ One-Hot Encoding kolom kategorikal
# =========================
categorical_cols = ["gender", "smoking_history", "location"]  # semua kolom kategori
for col in categorical_cols:
    X[col] = X[col].astype(str)

X_encoded = pd.get_dummies(X, columns=categorical_cols)

# Simpan daftar kolom training
model_columns = X_encoded.columns.tolist()
pickle.dump(model_columns, open("model_columns.pkl", "wb"))
print("✅ model_columns.pkl berhasil dibuat")

# =========================
# 3️⃣ Balancing dengan TomekLinks
# =========================
tl = TomekLinks()
X_res, y_res = tl.fit_resample(X_encoded, y)
print("Distribusi target setelah TomekLinks:", Counter(y_res))

# =========================
# 4️⃣ Latih XGBoost
# =========================
xgb = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)
xgb.fit(X_res, y_res)
print("✅ Model XGBoost dengan TomekLinks sudah dilatih")

# Simpan model
pickle.dump(xgb, open("model_xgb_tomek.pkl", "wb"))
print("✅ model_xgb_tomek.pkl berhasil dibuat")

# =========================
# 5️⃣ Prediksi data baru
# =========================
data_baru = pd.read_csv("diabetes_dataset.csv")  # dataset baru tanpa target

# One-Hot Encoding kolom kategorikal
for col in categorical_cols:
    data_baru[col] = data_baru[col].astype(str)
data_baru_encoded = pd.get_dummies(data_baru, columns=categorical_cols)

# Tambahkan kolom yang hilang agar sesuai training
for c in model_columns:
    if c not in data_baru_encoded.columns:
        data_baru_encoded[c] = 0

# Urutkan kolom sesuai training
data_baru_encoded = data_baru_encoded[model_columns]

# Prediksi
model_xgb = pickle.load(open("model_xgb_tomek.pkl", "rb"))
data_baru["prediksi_diabetes"] = model_xgb.predict(data_baru_encoded)

# =========================
# 6️⃣ Simpan hasil prediksi
# =========================
data_baru.to_csv("hasil_prediksi_xgb_tomek.csv", index=False)
print("✅ Hasil prediksi tersimpan di 'hasil_prediksi_xgb_tomek.csv'")

✅ model_columns.pkl berhasil dibuat
